### ISSUE TITLE
Entries are not visible

### ISSUE THREAD

**Issue by Romikanoni** [WoodyLetsCode/WLED-GUI#2]
Hello,

I have added my various controllers. Unfortunately they are not displayed.
But when deleting them they are visible.

![image](https://user-images.githubusercontent.com/50908826/95014324-5cd6f200-0646-11eb-934a-048127a0c011.png)
![image](https://user-images.githubusercontent.com/50908826/95014330-63fe0000-0646-11eb-900a-bccda43ffa2a.png)

**Comment by WoodyLetsCode** [comment]
Hello,
thank you for reporting this issue!
Did you do anything special before they were not displayed? 
Since when did you notice this bug?

**Comment by Romikanoni** [comment]
Hello,

thank you very much for the quick response!

I have never used wled-gui before and am just about to use it for the first time.
I added the controllers manually via the + in the upper right corner, nothing more.

Sorry for the little Information :/

Are there debug logs of the program that can provide further information?

Greetings

Von: Woody<mailto:notifications@github.com>
Gesendet: Sonntag, 4. Oktober 2020 14:29
An: WoodyLetsCode/WLED-GUI<mailto:WLED-GUI@noreply.github.com>
Cc: Romikanoni<mailto:roman.glorim@live.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [WoodyLetsCode/WLED-GUI] Entries are not visible (#2)


Hello,
thank you for reporting this issue!
Did you do anything special before they were not displayed?
Since when did you notice this bug?

**Comment by WoodyLetsCode** [comment]
Hello,
can you please run [this](http://www.mediafire.com/file/9tdwyxudaknume5/WLED-win32-x64_devtools.zip/file) version of wled-gui?
This version has developer options enabeld.
After you start the program it opens the developer tools. Please go to Console and send me a screenshot.
Make sure Console log level is set to default.
Please don't forget to reload, because some errors you only see at the beginning. (STRG + R to reload)
Switch between menu and deletings mode and look if there are any errors printed to console.
I want to check if there are any errors.

![grafik](https://user-images.githubusercontent.com/27882680/95111416-c0911600-073f-11eb-904d-82abe5e69bf4.png)


After that go to Application > Local Storage > file:// and send me a Screenshot.
Now send me all your local storage data. (key and value)
You can double click it and copy & paste it.
With this values i hope i can reproduce your issue.

![grafik](https://user-images.githubusercontent.com/27882680/95111644-1796eb00-0740-11eb-8d13-61a0e7851fe6.png)



Thank you very much!

**Comment by Romikanoni** [comment]
Hello, thank you for the response!



![image](https://user-images.githubusercontent.com/50908826/95116047-bc1c2b80-0746-11eb-9c1d-0b267e1b5156.png)


lights --> [{"name":"Nachttisch","ip":"192.168.2.230","online":true},{"name":"Vitrine","ip":"192.168.2.245","online":true}]

![image](https://user-images.githubusercontent.com/50908826/95116230-01d8f400-0747-11eb-8059-42b24b25f108.png)

**Comment by WoodyLetsCode** [comment]
Hello,
thank you very much! I found the bug and fixed it. 😄 
I published a new release. You can find it [here](https://github.com/WoodyLetsCode/WLED-GUI/releases/tag/v0.4.1).
Can you tell me if this has fixed your problem?

**Comment by Romikanoni** [comment]
Hello,

thanks a lot! It works now!

![image](https://user-images.githubusercontent.com/50908826/95121511-6c8e2d80-074f-11eb-8230-c8931fb9efbf.png)

thanks for the quick help!

**Comment by WoodyLetsCode** [comment]
Thank you for reporting this!
